name: Construir Lógica de Proyectos Ride

on:
  push:
    branches:
      - main

jobs:
  construir:
    name: Construir Lógica
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configurar Node
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Cache de NPM
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Instalar Dependencias
        run: npm install

      - name: Crear Build
        run: npm run build

  creartag:
    name: Crear Tag
    needs: construir
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Crear tag
        uses: Klemensas/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.MY_ACCESS_TOKEN }}"
          tag_prefix: "v"
